name: ci-workflow
on: [push]
jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Install cfn_nag
        run: |
          gem install cfn-nag
      - name: cfn_nag 
        run: |
          cfn_nag_scan --input-path template.yaml
      - name: Install cfn-lint
        run: |
          pip install cfn-lint
      - name: cfn-lint 
        run: |
          cfn-lint template.yaml
      - name: Install Bandit
        run: |
          pip install bandit
      - name: Bandit check
        run: |
          bandit -r rss_webhook.py --confidence-level high
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html