name: ci-workflow
on: [push]
jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repository
        uses: actions/checkout@v3
      - name: install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: install Ruby 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: install cfn_nag
        run: |
          gem install cfn-nag
      - name: cfn_nag 
        run: |
          cfn_nag_scan --input-path template.yaml
      - name: install cfn-lint
        run: |
          pip install cfn-lint
      - name: cfn-lint 
        run: |
          cfn-lint template.yaml
      - name: install bandit
        run: |
          pip install bandit
      - name: bandit checks
        run: |
          bandit -r rss_webhook.py --confidence-level high
      - name: install homebrew and git-secrets
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew upgrade
          brew install git-secrets
      - name: git-secrets
        run: |
          git secrets --scan
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: unit tests
        run: |
          pytest